#!/bin/bash

brew tap aws/tap
brew install aws-sam-cli
TMPDIR=$(mktemp -d)
pushd $TMPDIR
curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip" -o "sessionmanager-bundle.zip"
unzip "sessionmanager-bundle.zip"
sudo python3 sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
popd
rm -r $TMPDIR
unset TMPDIR
