#!/bin/sh

brew tap homebrew/cask-fonts
brew install --cask font-jetbrains-mono

osascript -e "tell application \"Terminal\" to set font name of settings set \"Pro\" to \"JetBrainsMono Nerd Font\""
osascript -e "tell application \"Terminal\" to set default settings to settings set \"Pro\""
