#!/bin/sh

NERDFONT=$(mktemp)
curl -L --progress-bar https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip -o "$NERDFONT"
sudo unzip -o -q "$NERDFONT" -d /Library/Fonts
sudo rm -f "$NERDFONT" /Library/Fonts/*Windows*

osascript -e "tell application \"Terminal\" to set font name of settings set \"Pro\" to \"JetBrainsMono Nerd Font\""
osascript -e "tell application \"Terminal\" to set default settings to settings set \"Pro\""
