#!/bin/bash

setup yay

yay -S --noconfirm direnv
sed '2i \\nexport DIRENV_LOG_FORMAT=' ~/.zshrc
[ -f ~/.zshrc ] && echo 'eval "$(direnv hook zsh)"' >> ~/.zshrc
get assets/direnvrc ~/.config/direnv/direnvrc
eval "$(direnv hook bash)"
