#!/bin/bash

install go go-tools

mkdir -p ~/{.local,Workspace}/go/bin
sed '2i export GOPATH="$HOME/.local/go:$HOME/Workspace/go"' ~/.zshrc
sed '2i \\nexport PATH="$HOME/.local/go/bin:$PATH"' ~/.zshrc
