#!/bin/bash

available go && return

install go go-tools

mkdir -p ~/{.local,Workspace}/go/bin
sed -i '2i export GOPATH="$HOME/.local/go:$HOME/Workspace/go"' ~/.zshrc
sed -i '2i \\nexport PATH="$HOME/.local/go/bin:$PATH"' ~/.zshrc
