#!/bin/sh

setup zsh

install noto-fonts noto-fonts-emoji mesa sway swaylock swayidle bemenu alacritty mako kanshi playerctl brightnessctl wl-clipboard waybar grim slurp waybar wofi pipewire xdg-desktop-portal xdg-desktop-portal-wlr libnotify

cat << EOF > .zshenv
export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=sway
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]]; then
  XKB_DEFAULT_LAYOUT=es exec sway
fi
EOF

sed -i '2i \\nexport GDK_BACKEND=wayland' ~/.zshrc
get assets/sway/alacritty.yml ~/.config/alacritty/alacritty.yml
get assets/sway/waybar.json ~/.config/waybar/config
get assets/sway/waybar.css ~/.config/waybar/style.css
get assets/sway/wofi.css ~/.config/wofi/style.css
for pkg in sway mako kanshi
do
  get assets/sway/"${pkg}".conf ~/.config/"${pkg}"/config
done

mkdir ~/{Documents,Downloads,Music,Pictures,Videos,Workspace}
get assets/user-dirs.dirs ~/.config/user-dirs.dirs
