#!/bin/sh

setup git

git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
pip install -U jedi-language-server
install lua-language-server
npm install --global @fsouza/prettierd
