#!/bin/sh

setup bw
setup tools

mkdir -p ~/.ssh
bw get item "fb21d443-4f27-4812-a404-aca401096867" | jq -r ".notes" | gpg --import
echo "5\ny\n" | gpg --command-fd 0 --expert --edit-key 0E5F27342AF9AFB6FCE9504635AB7E86500DD327 trust
gpg --export-ssh-key gga@kialo.com > ~/.ssh/id_card.pub
chmod 0600 ~/.ssh/id_card.pub
echo "enable-ssh-support" > ~/.gnupg/gpg-agent.conf
get assets/zsh/gpg.zsh ~/.config/zsh/gpg.zsh
echo ". ~/.config/zsh/gpg" >> ~/.zshrc

install yubikey-manager
sudo systemctl start pcscd.service
sudo systemctl enable pcscd.service
