#!/bin/sh

setup bw gpg direnv

install yubikey-manager
sudo systemctl start pcscd.service
sudo systemctl enable pcscd.service
gpg --card-status || (echo "Cannot detect Yubikey" && exit 1)

bwget "fb21d443-4f27-4812-a404-aca401096867" | gpg --import
echo "0E5F27342AF9AFB6FCE9504635AB7E86500DD327:6" | gpg --import-ownertrust
gpg --export-ssh-key gga@kialo.com > ~/.ssh/id_card.pub
chmod 0600 ~/.ssh/id_card.pub
echo "enable-ssh-support" > ~/.config/gnupg/gpg-agent.conf
get assets/zsh/gpg.zsh ~/.config/zsh/gpg.zsh
echo ". ~/.config/zsh/gpg.zsh" >> ~/.zshrc
. ~/.config/zsh/gpg.zsh
grep 'Host kialo.github.com' ~/.ssh/config > /dev/null 2>&1 || cat << EOF >> ~/.ssh/config

Host kialo.github.com
  Hostname github.com
  IdentityFile ~/.ssh/id_card.pub
  IdentitiesOnly yes
EOF

install gopass
git clone git@kialo.github.com:gga-kialo/secrets.git ~/.local/share/gopass/stores/root
git clone git@kialo.github.com:kialo/secrets.git ~/.local/share/gopass/stores/kialo
get assets/gopass.yml ~/.config/gopass/config.yml

install pyenv python-snappy
pyenv install 3.8.7

export KIALO_ROOT=~/Workspace/kialo/kialo
mkdir -p ~/Workspace/kialo
git clone git@kialo.github.com:kialo/kialo.git $KIALO_ROOT
cd $KIALO_ROOT || exit
get assets/kialo/envrc $KIALO_ROOT/.envrc
direnv allow
pip install flake8 mypy black jedi pynvim msgpack
pip install -r $KIALO_ROOT/backend/requirements-dev.txt
download-binaries

mkdir -p $KIALO_ROOT/.aws
sed 's/USERNAME/gga/' $KIALO_ROOT/deveopment/aws/aws_config/profiles > $KIALO_ROOT/.aws/config
bwget "1cfa3817-fe47-41b9-a7cd-acae01522f82" > $KIALO_ROOT/.aws/credentials
chmod 0600 $KIALO_ROOT/.aws/credentials

get assets/kialo/vimrc $KIALO_ROOT/.vimrc
