#!/bin/bash

export KIALO_ROOT=~/Workspace/kialo
export PATH="$KIALO_ROOT/development/bin:$PATH"
export AWS_CONFIG_FILE=$KIALO_ROOT/.aws/credentials

layout python ~/.pyenv/versions/3.8.7/bin/python
add_extra_vimrc
