[[ -z "$PS1" ]] && return

export CARGO_HOME="~/.config/cargo"

export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export PATH=$HOME/.local/bin:$PATH

export HISTCONTROL="ignorespace:erasedups"
export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd *"
export HISTFILE=~/.local/zsh/history
export HISTSIZE=25000
export SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

export EDITOR='vi'
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export PAGER="less"
export KEYTIMEOUT=1

export CLICOLOR=1  # OSx
export COMPLETION_WAITING_DOTS="true"

setopt INC_APPEND_HISTORY
setopt NO_BEEP
setopt RM_STAR_WAIT
setopt NOCLOBBER
setopt EXTENDED_GLOB
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
export DIRSTACKSIZE=10

bindkey -v

zstyle ':completion:*' special-dirs true
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
autoload -Uz compinit
compinit

autoload -z edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

. ~/.config/zsh/p10k/powerlevel10k.zsh-theme
. ~/.config/zsh/p10k.zsh
. ~/.config/zsh/aliases.zsh
