[[ -z "$PS1" ]] && return

export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export PATH=$HOME/.local/bin:$PATH

export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd *"
export HISTFILE=~/.local/zsh/history
export HISTSIZE=25000
export SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

export EDITOR='vi'
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export PAGER="less"

export CLICOLOR=1  # OSx
export COMPLETION_WAITING_DOTS="true"

# Python
export VIRTUAL_ENV_DISABLE_PROMPT=1
export PYTHONBREAKPOINT="pdb.set_trace"

setopt INC_APPEND_HISTORY
setopt NO_BEEP
setopt RM_STAR_WAIT
setopt NOCLOBBER

bindkey -v

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

. ~/.config/zsh/p10k/powerlevel10k.zsh-theme
. ~/.config/zsh/p10k.zsh
