#!/bin/sh

[ -n "$CONTAINER" ] || ls ~/.local/share/fonts/JetBrains* > /dev/null 2>&1 && return

setup zip

available fc-cache || install fontconfig
NERDFONT=$(mktemp)
curl -L --progress-bar https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip -o "$NERDFONT"
mkdir -p /usr/share/fonts/nerdfonts
unzip -o -q "$NERDFONT" -d /usr/share/fonts/nerdfonts
get assets/fontconfig/local.conf /etc/fonts/local.conf
fc-cache -vf /usr/share/fonts/nerdfonts
rm "$NERDFONT"

if available gnome-terminal
then
  PROFILE=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d "'")
  gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE/ font 'JetBrainsMono Nerd Font Regular 12'
  gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$PROFILE/ use-system-font false
fi
