#!/bin/sh

setup zsh

available fzf || install fzf
curl -sSL https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh -o ~/.config/zsh/fzf.zsh
curl -sSL https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh >> ~/.config/zsh/fzf.zsh
grep '. ~/.config/zsh/fzf.zsh' ~/.zshrc || echo '. ~/.config/zsh/fzf.zsh 2> /dev/null' >> ~/.zshrc
