#!/bin/sh

available git || install git
[[ ! $(uname -a) =~ "^Linux rpi" ]] && install git-delta
get assets/gitignore ~/.gitignore_global
get assets/gitconfig ~/.gitconfig
[ mac ] && xcode-select --install
