#!/bin/sh

install python3-pip || install python-pip
pip3 install --user --upgrade IPython
if [ -f ~/.zshrc ]
then
  get assets/zsh/python.zsh ~/.config/zsh/python.zsh
  grep -q '. ~/.config/zsh/python.zsh' ~/.zshrc || echo '. ~/.config/zsh/python.zsh' >> ~/.zshrc
fi
get assets/flake8 ~/.config/flake8
