#!/bin/sh

available pip3 || install python3-pip || install python-pip
pip3 install --user --upgrade IPython
if [ -f ~/.zshrc ]
then
  sed '2i\
export VIRTUAL_ENV_DISABLE_PROMPT=1\
export PYTHONBREAKPOINT="ipdb.set_trace"
' ~/.zshrc
  [ mac ] && sed "s/export PATH=/export PATH=\/Users\/$USER\/Library\/Python\/3.9\/bin:/" ~/.zshrc
fi
get assets/flake8 ~/.config/flake8
