#!/bin/sh

setup zsh

install tmux
get assets/tmux ~/.config/tmux
get assets/zsh/tmux.zsh ~/.config/zsh/tmux.zsh
grep '. ~/.config/zsh/tmux.zsh' ~/.zshrc || sed -i '36i. ~/.config/zsh/tmux.zsh\n' ~/.zshrc

if available fzf
then
  curl -sSL https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux -o ~/.local/bin/fzf-tmux
  chmod +x ~/.local/bin/fzf-tmux
fi
