#!/bin/sh

setup git fonts python

install neovim
[ -d ~/.config/nvim ] || git clone --depth=1 https://github.com/Funk66/vim.git ~/.config/nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

if [ -f /usr/bin/vim ]
then
  if [ ! -f ~/.local/bin/vim ]
  then
    mkdir -p ~/.local/bin
    ln -s "$(command -v nvim)" ~/.local/bin/vim
  fi
else
  sudo ln -s "$(command -v nvim)" /usr/bin/vim
fi

pip3 install --upgrade --user flake8 mypy black jedi pynvim msgpack
available npm && sudo npm i -g eslint tslint stylelint neovim
nvim +PackerSync +qa

if [ -f ~/.zshrc ]
then
  sed -i "s/EDITOR='vi'/EDITOR='nvim'/" ~/.zshrc
fi
