#!/bin/sh

setup git fonts python node rust

if [ "$INSTALLER" = "apt" ]; then
	SRC=$(mktemp -d)
	install cmake gettext python3-venv python3-pip
	git clone https://github.com/neovim/neovim "$SRC"
	cd "$SRC" || exit
	git checkout stable
	make CMAKE_BUILD_TYPE=Release
	sudo make install
	sudo cp build/bin/nvim /usr/local/bin/nvim
	cd - || exit
else
	install neovim
fi

if [ -d ~/.config/nvim ]; then
	mv ~/.config/nvim "$HOME/.config/nvim-$(date +%Y%m%d)"
fi

git clone https://github.com/funk66/vim ~/.config/nvim

if [ -f ~/.zshrc ]; then
	sed "s/EDITOR='vi'/EDITOR='nvim'/" ~/.zshrc
	echo "alias vim=nvim" >>~/.config/zsh/aliases.zsh
	# shellcheck source=assets/zsh/aliases.zsh
	. ~/.config/zsh/aliases.zsh
fi
