#!/bin/zsh

setup bw gpg direnv

[ mac ] && ARGS=--ignore-dependencies || ARGS=
install yarn "$ARGS"

if [ ! mac ]; then
  sudo systemctl enable --now pcscd.service
fi
gpg --card-status || (echo "Cannot detect Yubikey" && exit 1)

bwget "fb21d443-4f27-4812-a404-aca401096867" | gpg --import
echo "0E5F27342AF9AFB6FCE9504635AB7E86500DD327:6" | gpg --import-ownertrust
gpg --export-ssh-key gga@kialo.com > ~/.ssh/id_card.pub
chmod 0600 ~/.ssh/id_card.pub
grep 'Host kialo.github.com' ~/.ssh/config > /dev/null 2>&1 || cat << EOF >> ~/.ssh/config

Host kialo.github.com
  Hostname github.com
  IdentityFile ~/.ssh/id_card.pub
  IdentitiesOnly yes

Match host * exec "gpg-connect-agent UPDATESTARTUPTTY /bye"
EOF

git clone git@kialo.github.com:gga-kialo/secrets.git ~/.local/share/gopass/stores/root
git clone git@kialo.github.com:kialo/secrets.git ~/.local/share/gopass/stores/kialo
get assets/gopass ~/.config/gopass/config
sed "s|~|$HOME|" ~/.config/gopass/config
gopass sync

install pyenv

export KIALO_ROOT=~/Workspace/kialo/kialo
mkdir -p ~/Workspace/kialo/kialo
git clone git@kialo.github.com:kialo/kialo.git $KIALO_ROOT
PYTHON_VERSION=$(cat $KIALO_ROOT/.python-version)
pyenv install "$PYTHON_VERSION"
pushd $KIALO_ROOT || exit
gopass -n tools/envrc > $KIALO_ROOT/../.envrc
gopass -n tools/kialo/envrc > $KIALO_ROOT/.envrc
gopass -n tools/k8s-resources/envrc > $KIALO_ROOT/../k8s-resources/.envrc
direnv allow
python -m venv $KIALO_ROOT/../.direnv/poetry
npm install
npm run setup:backend
echo 'plugin_cache_dir = "$KIALO_ROOT/.terraform.d/plugin-cache"' > $KIALO_ROOT/.terraformrc
mkdir -p $KIALO_ROOT/.terraform.d/plugin-cache
download-binaries

mkdir $KIALO_ROOT/../bin

mkdir -p $KIALO_ROOT/.aws
gopass -n aws/credentials > $KIALO_ROOT/.aws/credentials
chmod 0600 $KIALO_ROOT/.aws/credentials

confgit() {
    git config user.name "Guillermo Guirao Aguilar"
    git config user.email "gga@kialo.com"
    git config user.signingkey E152A4F19F57F9BD
    git config commit.gpgsign true
    git config blame.ignoreRevsFile .git-blame-ignore-revs
    pre-commit install -f --install-hooks -t pre-commit -t commit-msg
}

confgit

cat << EOF >> ~/.config/zsh/aliases.zsh
alias k='kubectl'
alias kk='pushd ~/Workspace/kialo/kialo > /dev/null'
alias k8='pushd ~/Workspace/kialo/k8s-resources > /dev/null'
alias assume='. $KIALO_ROOT/development/aws/assume_role.sh'
alias eks='. $KIALO_ROOT/.kube/eks.zsh'
EOF

cat << EOF >> ~/.zshrc
source <(kubectl completion zsh)
complete -o default -F __start_kubectl k
EOF

mkdir -p $KIALO_ROOT/.{aws,kube}
chmod 700 $KIALO_ROOT/.{aws,kube}
gopass -n tools/eks.zsh > $KIALO_ROOT/.kube/eks.zsh
gopass -n aws/credentials > $KIALO_ROOT/.aws/credentials
get assets/kialo/kns.zsh $KIALO_ROOT/../bin/kns
get assets/kialo/rotate_aws.zsh $KIALO_ROOT/../bin/rotate_aws
chmod +x $KIALO_ROOT/../bin/{kns,rotate_aws,eks}

popd

git clone git@kialo.github.com:kialo/k8s-resources.git $KIALO_ROOT/../k8s-resources
pushd $KIALO_ROOT/../k8s-resources
confgit
$KIALO_ROOT/../.direnv/python-$PYTHON_VERSION/bin/pip install -r $KIALO_ROOT/../k8s-resources/requirements.txt
popd

cat << EOF >> $KIALO_ROOT/.git/hooks/prepare-commit-msg
#!/bin/sh

TICKET_NUM=\$(git rev-parse --symbolic-full-name --abbrev-ref HEAD | grep -Eo 'PM-\d{5}')
if [ -n "\$TICKET_NUM" ]; then
  COMMIT_MSG=\$(cat "\$1")
  if ! echo "\$COMMIT_MSG" | grep -qE '^(PM-\d{5}|Merge|Revert|\[)'; then
    echo "\$TICKET_NUM \$COMMIT_MSG" > "\$1"
  fi
fi
EOF
chmod +x $KIALO_ROOT/.git/hooks/prepare-commit-msg
ln -s $KIALO_ROOT/.git/hooks/prepare-commit-msg $KIALO_ROOT/../k8s-resources/.git/hooks/prepare-commit-msg
