#!/bin/sh

setup bw gpg direnv

sudo systemctl enable --now pcscd.service
gpg --card-status || (echo "Cannot detect Yubikey" && exit 1)

bwget "fb21d443-4f27-4812-a404-aca401096867" | gpg --import
echo "0E5F27342AF9AFB6FCE9504635AB7E86500DD327:6" | gpg --import-ownertrust
gpg --export-ssh-key gga@kialo.com > ~/.ssh/id_card.pub
chmod 0600 ~/.ssh/id_card.pub
grep 'Host kialo.github.com' ~/.ssh/config > /dev/null 2>&1 || cat << EOF >> ~/.ssh/config

Host kialo.github.com
  Hostname github.com
  IdentityFile ~/.ssh/id_card.pub
  IdentitiesOnly yes

Match host * exec "gpg-connect-agent UPDATESTARTUPTTY /bye"
EOF

git clone git@kialo.github.com:gga-kialo/secrets.git ~/.local/share/gopass/stores/root
git clone git@kialo.github.com:kialo/secrets.git ~/.local/share/gopass/stores/kialo
get assets/gopass.yml ~/.config/gopass/config.yml
sed "s|~|$HOME|" ~/.config/gopass/config.yml
gopass sync

install pyenv
PYTHON_VERSION=3.10.4
pyenv install $PYTHON_VERSION

export KIALO_ROOT=~/Workspace/kialo/kialo
mkdir -p ~/Workspace/kialo/kialo
git clone git@kialo.github.com:kialo/kialo.git $KIALO_ROOT
pushd $KIALO_ROOT || exit
get assets/kialo/envrc $KIALO_ROOT/../.envrc
direnv allow
$KIALO_ROOT/../.direnv/python-$PYTHON_VERSION/bin/pip install flake8 mypy black jedi pynvim msgpack awscli
$KIALO_ROOT/../.direnv/python-$PYTHON_VERSION/bin/pip install -r $KIALO_ROOT/backend/requirements-dev.txt
echo 'plugin_cache_dir = "$KIALO_ROOT/.terraform.d/plugin-cache"' > $KIALO_ROOT/.terraformrc
download-binaries
pre-commit install -f --install-hooks -t pre-commit -t commit-msg -t pre-push

mkdir $KIALO_ROOT/../bin

mkdir -p $KIALO_ROOT/.aws
gopass -n aws/credentials > $KIALO_ROOT/.aws/credentials
chmod 0600 $KIALO_ROOT/.aws/credentials

get assets/kialo/vimrc $KIALO_ROOT/.vimrc

git config user.name 'Guillermo Guirao Aguilar'
git config user.email 'gga@kialo.com'
git config commit.gpgsign true
git config blame.ignoreRevsFile .git-blame-ignore-revs

pre-commit install -f --install-hooks -t pre-commit -t commit-msg

cat << EOF >>  /dev/null > ~/.config/zsh/aliases.zsh
alias k='kubectl'
alias kk='pushd ~/Workspace/kialo/kialo > /dev/null'
alias k8='pushd ~/Workspace/kialo/k8s-resources > /dev/null'
alias otp="ykman --device 6931997 oath accounts code aws --single | pbcopy"
EOF

mkdir -p $KIALO_ROOT/.kube
chmod 700 $KIALO_ROOT/.{aws,kube}
gopass -n aws/assume > $KIALO_DIR/../bin/assume
gopass -n aws/eks > $KIALO_DIR/../bin/eks
get assets/kialo/kns.zsh $KIALO_ROOT/../bin/kns
get assets/kialo/rotate_aws.zsh $KIALO_ROOT/../bin/rotate_aws
chmod +x $KIALO_ROOT/../bin/{kns,rotate_aws,assume,eks}

confgit() {
    git config user.name "Guillermo Guirao Aguilar"
    git config user.email "gga@kialo.com"
    git config user.sigingkey 35AB7E86500DD327
    git config commit.gpgsign true
}

confgit()
popd

git clone git@kialo.github.com:kialo/k8s-resources.git $KIALO_ROOT/../k8s-resources
pushd $KIALO_ROOT/../k8s-resources
pre-commit install -f --install-hooks -t pre-commit -t commit-msg
config()
popd
