#!/bin/sh

setup git fonts

available zsh || install zsh
mkdir -p ~/.local/zsh
get assets/zshrc ~/.zshrc
get assets/zsh/p10k.zsh ~/.config/zsh/p10k.zsh
get assets/zsh/aliases.zsh ~/.config/zsh/aliases.zsh
[ -d ~/.config/zsh/p10k ] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/p10k
sudo chsh -s "$(command -v zsh)" "$USER"

if available fzf && ! available fzf-tmux
then
  setup fzf
fi

if available nvim
then
  sed "s/EDITOR='vi'/EDITOR='lvim'/" ~/.zshrc
fi

if ! mac
then
    sudo ln -s /usr/bin/zsh /bin/zsh
fi
