#!/bin/sh

install zsh
sudo apt install tmux
curl -sSL "$URL"/assets/tmux -o ~/.config/tmux
curl -sSL "$URL"/assets/zsh/tmux -o ~/.config/zsh/tmux
grep '. ~/.config/zsh' ~/.zshrc || echo '. ~/.config/zsh' > ~/.zshrc
