#!/bin/sh

install git

sudo apt install -y neovim
git clone --depth=1 https://github.com/Funk66/vim.git ~/.config/nvim
curl -sSL https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim -o ~/.config/nvim/autoload/plug.vim --create-dirs
get assets/vim .config/nvim/init.vim
sudo ln -s "$(command -v nvim)" /usr/bin/vim
vim +PlugInstall +qa

if command -v pip > /dev/null
then
  pip install --upgrade --user flake8 mypy black
fi

if command -v npm > /dev/null
then
  npm i -g eslint tslint stylelint
fi
