#!/bin/sh

install git

sudo apt install -y zsh
get assets/zshrc ~/.zshrc
get assets/zsh/p10k.zsh ~/.config/zsh/p10k.zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/p10k
sudo chsh -s "$(command -v zsh)"
if command -v fzf > /dev/null && ! command -v fzf-tmux > /dev/null
then
  install fzf
fi
